### ISSUE TITLE
Set additional enchantments to false in config, but they still appear in-game with no effect

### ISSUE THREAD

**Issue by elbakramer** [Dqu1J/additionaladditions#10]
#### Versions:

* Minecraft: 1.17.1
* Fabric: 0.11.6
* Mod: AdditionalAdditions-2.1.3.jar

#### Content:

Config:
```json
{
  "version": 4,
  "GildedNetherite": true,
  "Wrench": true,
  "AmethystLamp": true,
  "EnchantmentPrecision": false,
  "EnchantmentSpeed": false,
  "CompostableRottenFlesh": true,
  "GlowStick": true,
  "MysteriousBundle": true,
  "Crossbows": true,
  "MusicDiscs": true,
  "RoseGold": true,
  "FoodItems": true,
  "Potions": false,
  "WateringCan": true,
  "CopperPatina": true,
  "Ropes": true,
  "TridentShard": false,
  "DepthMeter": true
}
```

* Expected behavior: Work like those enchantments were never existed.
* Current behavior: Those enchantments will still be shown as an option in enchantment table, as enchanted books that librarians sell, as an enchanted item in loot. But they are useless since there is no actual effect due to the config value set to false.

Is this an intended behavior?
Possible fix might be like, registering those enchantments only when their config value are set to true?

**Comment by Dqu1J** [comment]
That is intended. I cant just not register them because worlds will become incompatible when config changes.
