### ISSUE TITLE
Fails to Launch 1.18.rc2

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Dqu1J/additionaladditions#14]
With the release of 1.18 RC2 AdditionalAdditions-3.0.0 for 1.18 fails to launch

Mod 'Additional Additions' (additionaladditions) requires "version 1.18-rc.1" of 'Minecraft' (minecraft), but only the wrong version is present: 1.18-rc.2!

**Comment by susan3333333** [comment]
Quick player fix for this issue on several mods, it works fine on mine after :).

Just edit the fabric.mod.json file in the .jar, at line 34:
Where it says:
    "minecraft": "1.18-rc.1",
Change to:
     "minecraft": "1.18-rc.2",

**Comment by ClaudiusMinimus** [comment]
Thanks, I realize that, but I am using your mod in my mod pack which will be published soon. I can't have players modifying files, they just won't play it.

**Comment by susan3333333** [comment]
Errr.....not my mod, was just posting to help a fellow player.

**Comment by ClaudiusMinimus** [comment]
Cool, thanks!

**Comment by Dqu1J** [comment]
Hey! The current release is for RC-1. Please, wait for the update.

**Comment by ClaudiusMinimus** [comment]
That's fine, just trying to get my mod pack read for release on the 30th
