### ISSUE TITLE
Spyglass Zoom mod high sensitivity when zooming

### ISSUE THREAD

**Issue by kxkxrxtx** [Dqu1J/additionaladditions#17]
Hey! I love your additions to the game, mostly for copper and amethyst use :D 
Anyway, with both mods related installed, the game freezes while sneaking with the Spyglass Crossbow.

Minecraft version: 1.18
Fabric version: 0.12.8
Additional Additions version: 3.0.0
Spyglass Zoom version: 1.0.2

Thanks in advantage!

**Comment by Dqu1J** [comment]
Unable to reproduce crashing/freezing, works for me. But the sensitivity is way too high

**Comment by Dqu1J** [comment]
Unable to reproduce__
