### ISSUE TITLE
Game Crashing/Save not loading after placing a wisteria sign?

### ISSUE THREAD

**Issue by dewwdrp** [Dqu1J/additionaladditions#19]
Basically exactly as the title says, everything was working fine until I decided to use a wisteria sign. I placed the sign and my game crashed, and now I can't load into the save I placed the sign down in either. Though I'm not sure why it would be the sign in particular, but I know it is because I've also placed the planks, logs, and stripped logs down in the same save before I attempted the sign, as it's a world that's a sort of testing world for when I download new mods. 

I'm not super concerned about losing that world in particular, but I thought it would be a good idea to let you know that it happened, I'm not sure if maybe I have a conflicting mod somewhere or maybe it's something else? I'm also uploading two crash logs, the first one is when the first crash happened, the second one is from trying to load into the save after removing the mod from my mods folder completely. I'm not sure if that will change anything in the log at all, but I thought it wouldn't hurt to share both just in case.
 
[crash-2021-12-12_01.18.28-client - First Crash.txt](https://github.com/Dqu1J/additionaladditions/files/7699950/crash-2021-12-12_01.18.28-client.-.First.Crash.txt)
[crash-2021-12-12_17.05.05-client - After Removing Mod.txt](https://github.com/Dqu1J/additionaladditions/files/7699951/crash-2021-12-12_17.05.05-client.-.After.Removing.Mod.txt)

**Comment by dewwdrp** [comment]
Apologies, posted in the wrong git, this is what happens when you have too many tabs open. Sorry about that!

**Comment by Dqu1J** [comment]
No problem!
