### ISSUE TITLE
Rose Gold Tools unable to mine not vanilla blocks

### ISSUE THREAD

**Issue by f-raZ0R** [Dqu1J/additionaladditions#2]
I'm honestly not even sure HOW you managed this. This thing's mining level is cursed, it can only mine vanilla ores, anything that requires a mining level above stone, and is modded, this thing can't mine.
Please fix, I don't want to have to carry around an iron pickaxe as well as this, just to be able to mine modded ores.

**Comment by Dqu1J** [comment]
What mod are you having isssues with?

**Comment by Dqu1J** [comment]
I am unable to reproduce that issue. Your issue is probably in the mod from where these blocks are. Contact that mod owner.

**Comment by f-raZ0R** [comment]
I contacted them, and the issue is back to being on your end, as apparently your pickaxe is not tagged with fabric:pickaxes.
