### ISSUE TITLE
Piglins can wear rose gold armor

### ISSUE THREAD

**Issue by ejektaflex** [Dqu1J/additionaladditions#22]
Piglins can wear rose gold, but they still attack anybody wearing it. This feels weird consistency-wise: Why would a piglin attack you for not having something he loves while wearing it himself? - it would be more consistent if they couldn't wear rose gold, or (preferably) if rose gold does not aggro piglins.

For now I've just added the armor pieces to the `#minecraft:piglin_loved` tag

**Comment by Dqu1J** [comment]
What do you mean by "they wear it"? That isn't intended.

**Comment by ejektaflex** [comment]
Yeah, I've twice seen a Piglin wearing it, and gotten the armor piece once they've died. 

My initial thoughts are:
1) The mob got equipped with it on spawn, similarly to zombies and skeletons when playing on Hard (but they usually only wear gold so this feels unlikely)
2) A player died to the piglin and the piglin put on their armor (also unlikely since we have a graves mod, so the player would not have dropped anything, but plausible since mobs that equip armor do not naturally despawn, which is a fun fact).

If it's option 2, then it's fine. However, option 1 just feels odd during gameplay if that is what is happening.

**Comment by Dqu1J** [comment]
Was that in a modpack, or vanilla additional additions?

**Comment by Dqu1J** [comment]
Unable to reproduce
