### ISSUE TITLE
Speed Enchantment

### ISSUE THREAD

**Issue by ChristopherTheBoss** [Dqu1J/additionaladditions#23]
I'm trying to learn to read code and I can't find where the 7% increase in speed from the Speed enchantment is implemented. Could you show me please?

I appreciate how configurable the mod is.

Edit 2: probably should have reached out on Discord.

**Comment by Dqu1J** [comment]
https://github.com/Dqu1J/additionaladditions/blob/main/src/main/java/dqu/additionaladditions/mixin/LivingEntityMixin.java

**Comment by ChristopherTheBoss** [comment]
Thank you @Dqu1J 
I'm going to conclude this non-issue with some runner's anecdotes:
By default Steve runs a 1600m (1 mile) in around 4:40. My best time is around 4:30. Having acquired Speed 1 boots, thanks to your mod, my ingame 1600 time would be close to 4:26. I view a 7% improvement to be approaching the limit to be gained from changing from a slow pair of running shoes to a fast pair of running shoes. 10% is theoretically obtainable but in reality, the Nike Vaporfly 4% is a shoe which markets itself as being able to improve a marathoner's running economy by 4% compared to its predecessors.
I posit that Speed I could reasonably increase player speed by 7% as the gains from non-performant to decently performant are easily had. Speed II could add an additional 4% to cap the Speed enchantment at 11%, as the gains from decently performant to exceedingly performant are rarer.
Equipment ought to be the least influential aspect of developing player movement speed, as an RPG system would allow players to improve their running by running more. Actually, if this were RLCraft I would suggest that equipment inhibit running speed by its weight...perhaps a penalty offsetable by an enchantment to make the gear lighter.
I am happy with my Speed I boots and won't be upgrading them unless I destroy my mile Personal Record.
