### ISSUE TITLE
CANT ADD MINECRAFT SEX MOD!!!!

### ISSUE THREAD

**Issue by vaykd** [Dqu1J/additionaladditions#25]
IM TRYING TO ADD THE MINECRAFT BEASTIEALTY MOD AND IT WONT SHOW UP WHEN I OPEN VALHELSIA

**Comment by Dqu1J** [comment]
Hello. I am very sorry to hear that you have issues when using Additional Additions. After reading carefully throughout your report, I have concluded that you may have encountered issues within a modpack named Valhelsia. If that is right, then please, contact the Valhelsia team. However, if that is not right, then I would need your latest log file, that can be found by you in the logs folder of your Minecraft data folder. Please, send me the logs, and I will try to do my best at resolving your issue. Now, I will close that issue. Please, reopen it when you have provided the logs required to fix that issue.

Best regards,
Dqu1J
