### ISSUE TITLE
Pocket Jukebox destroys NBT of Music Discs from Data Packs

### ISSUE THREAD

**Issue by Donovan2649** [Dqu1J/additionaladditions#26]
Not a Major issue here, just wanted to bring to your attention that any music disks added by data packs and not mods will be converted from the music disk u had to C18's 11 music disk. If it can just hold and remember nbt data I'm pretty sure they'd work properly with data pack disks.

**Comment by Dqu1J** [comment]
Hey! Thanks for reporting. Can you please link the datapack you have this issue with? Thanks!

**Comment by Dqu1J** [comment]
Closed because no info was provided in over a week.
