### ISSUE TITLE
[1.18.2][Fabric 0.13.3][AA 3.0.1] 

### ISSUE THREAD

**Issue by GalacticRuler** [Dqu1J/additionaladditions#44]
[latest (2).log](https://github.com/Dqu1J/additionaladditions/files/8545951/latest.2.log)

note: I am acting as a proxy for another user, and as such, testing possible causes is difficult

Game crashes at launch, after a clean installation of a set of mods. Other users with these same mods do not experience this crash. Last logged error I can understand easily mentions AA so I thought I'd bring it up

**Comment by Mira047** [comment]
Could you also send your config?

**Comment by GalacticRuler** [comment]
Somehow, the crashes have self-resolved for the user who that log belongs to....apologies for bothering you?....
