### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by aresociety** [Dqu1J/additionaladditions#8]
Hey,
I tried to contact you through this discord but that didn't work out, I worked on a korean translation you can feel free to use. Thank you!
I'm not sure I can upload a json file to issues so I posted it here.

https://github.com/aresociety/dqu1j-aa-ko-kr
(Accept the collaboration request on the translation repository)

**Comment by Dqu1J** [comment]
Hello! You should have cloned this repository, and after created a pull request. I will add these translations to Additional Additions after verifying they are correct via Google Translator. Thanks for contributing!

**Comment by Dqu1J** [comment]
Added by 9a4b5b5
@aresociety Can I add you to `Credits` list, please?
