### ISSUE TITLE
Sprinkler Item for Additional Additions

### ISSUE THREAD

**Issue by Frankiscophil** [Dqu1J/additionaladditions#9]
I'm liking a lot of cool stuff from this mod but I wanted to ask if maybe down the line, we can get a Sprinkler item that basically automates the Watering Can in a 9x9 radius similar to the OpenBlocks Sprinkler. Just a suggestion that I would like to see in this.

Thanks for taking the time to read this and keep up the good work!

**Comment by Dqu1J** [comment]
Thanks for the suggestion! I will consider that and reply later with my opinion on that.

**Comment by Dqu1J** [comment]
Won't be implemented probably. Still thinking of a way to make it feel vanilla.

**Comment by TheSpiderDungeon** [comment]
How about making it a slab you place above a 7x7 or 9x9 farm? Normal slab for a wider range, upside-down slab to allow you to automatically fill it. Both can be filled with a water bucket the same way you would a cauldron, and it fertilizes any crop in its radius once every couple of seconds. The water depletes a bit every time it does a watering cycle, but upside-down sprinklers can be filled by non-source water above it to let you chain multiple sprinklers together, while normal sprinklers can only be filled by a bucket.
